@startuml
skinparam shadowing false
skinparam linetype ortho
skinparam monochrome true
skinparam nodesep 70
skinparam ranksep 70
skinparam dpi 300

entity "ПОЛЬЗОВАТЕЛЬ" as user {
  * id : INTEGER <<PK>>
  --
  name : TEXT
  login : TEXT
  phone : TEXT
}

entity "КУРЬЕР" as courier {
  * id : INTEGER <<PK>>
  --
  name : TEXT
  login : TEXT
  phone : TEXT
}

entity "АДМИНИСТРАТОР" as admin {
  * id : INTEGER <<PK>>
  --
  name : TEXT
  login : TEXT
}

entity "ЗАКАЗ" as order {
  * id : INTEGER <<PK>>
  --
  user_id : INTEGER <<FK>>
  courier_id : INTEGER <<FK>>
  status : TEXT
  created_at : DATETIME
  delivery_address : TEXT
  total_amount : INTEGER
}

user ||--o{ order : ""
courier ||--o{ order : ""
admin ||--o{ courier : ""

@enduml