@startuml

start

:Авторизация пользователя;

:Создание заказа;

stop

@enduml

@startuml
start
:Поступление заявки на регистрацию\nкурьера в системе;
if (Нехватка курьеров?) then (Да)
  :Изменить статус курьера\nна "Принят";
else (Нет)
  :Изменить статус заявки\nна "В ожидании";
endif
stop
@enduml

@startuml
start
:Поступление заказа в систему;
if (Курьер доступен?) then (Да)
  :Изменить статус заказа на\n"Принято к доставке";
else (Нет)
  :Изменить статус заказа на\n"В ожидании";
endif
stop
@enduml

@enduml